In [16]:
import numpy as np


In [17]:
a = np.random.randint(10,50,20)
a

array([17, 36, 38, 42, 29, 11, 42, 25, 43, 44, 42, 40, 26, 28, 42, 30, 37,
       13, 33, 46])

In [18]:
np.sum(a)

664

In [19]:
c = np.prod([[1,2],[2,3]])

c

12

In [20]:
np.argmax(a)

19

In [21]:
b = np.random.randint(50,80,10)
b

array([76, 66, 58, 77, 60, 53, 55, 51, 60, 68])

In [22]:
np.max(b)

77

In [23]:
np.min(a)

11

In [24]:
np.argmin(b)

7

In [25]:
np.argmax(b)# argmax and argmin returns only the index position of the element

3

In [26]:
np.std(b) #Returns the standard deviation, a measure of the spread of a distribution,of the array elements. The standard deviation is computed for theflattened array by default, otherwise over the specified axis.

8.63944442658207

In [27]:
np.var(b)#Returns the standard deviation, a measure of the spread of a distribution,of the array elements. The standard deviation is computed for theflattened array by default, otherwise over the specified axis.

74.64

In [28]:
np.mean(b)# it is used to return the mean value

62.4

In [29]:
print(b)
np.median(b) # returns the meadian value (ie.) the middle value of the array

[76 66 58 77 60 53 55 51 60 68]


60.0

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.mod(10,4) # it is used to return the remainder of given  argument (the argument must be more or equal to two)

2

In [32]:
print(a)
np.amax(a)

[17 36 38 42 29 11 42 25 43 44 42 40 26 28 42 30 37 13 33 46]


46

In [33]:
np.amin(a)# it is also used to return the max o min value of the array

11

In [34]:
import numpy as np

In [35]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
np.shape(arr)

(10,)

In [37]:
arr_2 = arr.reshape(2,5)
arr_2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
arr_2[::]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
arr_2[0,2:]

array([12, 13, 14])

In [40]:
import numpy as np
rng = np. random.default_rng()
rng

Generator(PCG64) at 0x18D59013680

In [41]:
big_array = rng.random(10000000)
%timeit sum(big_array)# to check the time take for the particular function
%timeit np.sum(big_array)

1.73 s ± 58.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
23.9 ms ± 2.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
# MULTIDIMENTIONAL AGGREGATE FUNCTION

In [43]:
M = rng.integers(0,10,(3,4))
M

array([[0, 0, 1, 9],
       [9, 1, 9, 7],
       [0, 4, 1, 8]], dtype=int64)

In [44]:
M.min(axis=0)#column

array([0, 0, 1, 7], dtype=int64)

In [45]:
M.min(axis=1)#ROW

array([0, 1, 0], dtype=int64)

In [46]:
#OTHER AGGREGATE FUNCTIONS

In [47]:
sum,prod,mean,median ,argmax,argmin,min,max,std,var,percentile ,any,all

NameError: name 'prod' is not defined

In [ ]:
np.any(1,0)

In [ ]:
np.all(1,0)

In [ ]:
# COMPARISION OPERATOR

In [ ]:
x = np.array([1,2,3,4,5])

In [ ]:
 c =x<3
print(c)
type(c)

In [ ]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)

In [ ]:
x>3

In [ ]:
x!=3

In [ ]:
(2*x) == (x**2) # can also use np.equal ,np.less,np.greater,np.less_equal ,np.greater_equal

In [ ]:
rnd = np.random.default_rng(seed=1710)
x =rng.integers(10,size=(3,4))
x

# it only checks the condition np.NaN is used to import NaN value

In [ ]:
d= np.count_nonzero
d

### 30.05.2023

### BOOLEAN OPERATOR

In [ ]:
#mask---> amore powerfull pattern is used to boolean array as mask,to select pariticular subset of data .

In [ ]:
rnd = np.random.default_rng(seed=1710)
rnd
z =rng.integers(10,size=(3,4))
z

In [ ]:
w = x<5
print(w)

In [ ]:
c = x[x<6] #----> masking (made with help of indexing position so it named as masking)
print(c)

In [ ]:

rainy = (ranifall_num>0)
days = np.arange(365)
summer = (day>172) & (days<262)
print("median percip on rain days in 2015(mm)",np.medium(rainfall_num[rainy]))
print("median percip on non-summer rainy days(mm):",np.median(rainfall_num[rainy & ~ summer]))

In [ ]:
# & ----> and  |-----> or 


In [48]:
bool(42), bool(0)

(True, False)

In [49]:
bool( 42 and 0)

False

In [50]:
bool(42 or 0)

True

In [51]:
# bin()----> returns the binary value

In [52]:
bin(5)

'0b101'

In [53]:
bin(42 & 59)

'0b101010'

In [54]:
bin(42 & 59)

'0b101010'

In [55]:
bin(42 ^ 59)

'0b10001'

In [56]:
a = np.array([1,0,1,0,1,0], dtype=bool)
b =np.array([1,0,1,0,1,0], dtype=bool)
print( a |b)

[ True False  True False  True False]


In [57]:
r = np.arange(10)
print(r)
(r>5) & (r<8)

[0 1 2 3 4 5 6 7 8 9]


array([False, False, False, False, False, False,  True,  True, False,
       False])

In [58]:
 ###FANCY INDEXING ----> also known as vectorized indexing in which we pass array of indices in place of single scalar.

In [59]:
import numpy as np
fg = np.random.default_rng(seed=1710)
fg
c = fg.integers(100,size = 10)
c

array([78, 63, 95, 26, 14, 60, 78,  7, 11,  4], dtype=int64)

In [60]:
 t =[c [3],c[7],c[2]]
t

[26, 7, 95]

In [61]:
key = [3,7,2]
c[key]

array([26,  7, 95], dtype=int64)

In [62]:
key = np.array([[3,2],[5,0]])
d= c[key]
print(d)
type(d)

[[26 95]
 [60 78]]


numpy.ndarray

In [63]:
v  = np.arange(12).reshape(3,4) 
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
row  = np.array([0,1,2]) # see in the  form of row and column 1st is for row and second is for column 
col =  np.array([2,1,3])
v [row,col]

array([ 2,  5, 11])

In [65]:
h = np.arange(16).reshape(4,4)
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
row = np.array([0,1,2,3])
col = np.array([0,1,2,3])
h[row,col]

array([ 0,  5, 10, 15])

In [67]:
v  = np.arange(12).reshape(3,4) 
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
row  = np.array([0,1,2]) # see in the  form of row and column 1st is for row and second is for column 
col =  np.array([2,1,3])
v [row,col]

array([ 2,  5, 11])

In [69]:
v[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [70]:
v[row[:np.newaxis]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### COMBINED INDEXING|

In [71]:
print(v)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
v[2,[2,0,1]]   

array([10,  8,  9])

In [73]:
 arr= np.array([[[10,20,30,40],[1,2,3,4],[5,6,7,10],[15,16,17,19]],[[55,56,57,58],[41,42,43,44],[31,32,33,34],[21,22,23,24]]])
arr

array([[[10, 20, 30, 40],
        [ 1,  2,  3,  4],
        [ 5,  6,  7, 10],
        [15, 16, 17, 19]],

       [[55, 56, 57, 58],
        [41, 42, 43, 44],
        [31, 32, 33, 34],
        [21, 22, 23, 24]]])

In [74]:
ch = np.array([1])
row =np.array([0,1,2,3])
col = np.array([0,1,2,3])
arr_1 = arr[ch,row,col]
arr_1

array([55, 42, 33, 24])

In [75]:
ch = np.array([0])
row =np.array([0,1,2,3])
col = np.array([0,1,2,3])
arr_2 = arr[ch,row,col]
arr_2

array([10,  2,  7, 19])

In [76]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
arr_1 = arr.reshape(5,5)
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
dis = np.array([[[10,20,30,40],[1,2,3,4],[5,6,7,10],[15,16,17,19]],[[55,56,57,58],[41,42,43,44],[31,32,33,34],[21,22,23,24]],[[50,51,52,53],[60,61,62,63],[70,71,72,73],[85,86,87,88]]])
print(dis)    

[[[10 20 30 40]
  [ 1  2  3  4]
  [ 5  6  7 10]
  [15 16 17 19]]

 [[55 56 57 58]
  [41 42 43 44]
  [31 32 33 34]
  [21 22 23 24]]

 [[50 51 52 53]
  [60 61 62 63]
  [70 71 72 73]
  [85 86 87 88]]]


In [83]:
row = [0,1,2,3]
col = [0,1,2,3]
ch = [2]
kite = dis [ch,row,col]
print(kite)

[50 61 72 88]


In [89]:
row = [0,1,2,3]
col = [0,1,2,3]
ch = [0]
kite = dis [ch,row,col]
print(kite)

[10  2  7 19]


In [90]:
row = [0,1,2,3]
col = [0,1,2,3]
ch = [1]
kite = dis [ch,row,col]
print(kite)

[55 42 33 24]
