In [104]:
import numpy as np

In [105]:
arr = np.arange(10,50,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [106]:
np.shape(arr)

(20,)

In [107]:
a=arr.reshape(5,4)
a

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [108]:
a[:2,:2]

array([[10, 12],
       [18, 20]])

In [109]:
z= arr[arr>25]
print(z)

[26 28 30 32 34 36 38 40 42 44 46 48]


In [110]:
np.array([[5,8],[1,2]])

array([[5, 8],
       [1, 2]])

In [111]:
c=np.modf(0.5)
c

(0.5, 0.0)

In [112]:
b = np.random.randint(10,50,30)
print(b)

[22 18 37 48 47 16 38 23 16 15 41 17 30 40 40 19 19 48 31 47 46 23 27 37
 41 47 18 29 25 48]


In [113]:
np.shape(b)

(30,)

In [114]:
r=b.reshape(5,6) 
print(r)

[[22 18 37 48 47 16]
 [38 23 16 15 41 17]
 [30 40 40 19 19 48]
 [31 47 46 23 27 37]
 [41 47 18 29 25 48]]


In [115]:
r[:5,1:2]

array([[18],
       [23],
       [40],
       [47],
       [47]])

In [116]:
c = np.prod([[1,2],[2,3]])

c

12

In [117]:
import numpy as np
x = np.arange(1,101).reshape(10,10)/100
x

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [118]:
math = np.arange(10,30)
print(math)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [119]:
np.array(math)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [120]:
np.shape(math)

(20,)

In [121]:
math.reshape(5,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [122]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [124]:
mat[-2][-1]

20

In [125]:
mat[:3,2:3]

array([[ 3],
       [ 8],
       [13]])

In [126]:
mat[-1]

array([21, 22, 23, 24, 25])

In [127]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [128]:
np.max(math)

29

In [129]:
np.min(math)

10

In [130]:
np.argmin(math)

0

In [131]:
np.argmax(math)

19

In [132]:
print(math)
int(np.median(math))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


19

### linspace

 ### it is used to return the remainder of given  argument (the argument must be more or equal to two)

###vino

###random

###linspace







### it is used to return the remainder of given  argument (the argument must be more or equal to two)