In [1]:
import numpy as np

In [28]:
my_3Darray = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]] # 3D array 
b=(np.array(my_3Darray))
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [37]:
b[::,::]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [6]:
arr=np.arange(25)
print(np.array(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [7]:
arr.shape

(25,)

In [14]:
x=arr.reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 1],
       [21]])

In [25]:
my_3Darray[2][0][0]

1

In [27]:
ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
ar

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 4]]])

In [29]:
ar[1][1]

array([2, 3, 4])

In [4]:
import numpy as np
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
import numpy as np
a=np.eye(3,3)*6
print(a)

[[6. 0. 0.]
 [0. 6. 0.]
 [0. 0. 6.]]
